language: python
dist: xenial
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - AWS_DEFAULT_REGION=us-east-1
    - secure: "H1xbz9QUvgoNtDvY9K72YvUkGGVWiq5qL2IZDfG1y7scIKdUMZqvj2s/aB/UCw95POc1/SSo1vf5rtpvz7D4TTo+YW9y9ZLuHxetbGPnkql+lu/+HTpPJcr91pg4fEz4txhnAlJ+cdp3bITOvbuKYoUZ+toxiTf3wouETBikfGo="
    - secure: "JZRJyA7fGSHjEx8nIyCzhD9KLWbu4h1R5A+VLDuFN0FjCjALKjJxaIUwT8/xHT97FXbqTbN+xvFyWnKerVpGX1peNGifralm3tMl63QXdATaprsmENmM3fYRWYGqWhy+6a21hrxFZ+MdblFKWsFWq/TNbsLWYM3vahvZDe1eyck="

stages:
  - test
  - name: upload coverage
    if: repo = gmr/pamqp
  - name: deploy
    if: tag IS present

install:
  - pip install -r requirements.txt
  - pip install awscli
script:
  - nosetests
  - flake8
after_success: bin/upload-coverage.sh

jobs:
  include:
    - stage: upload coverage
      if: repo = gmr/pamqp
      python: 3.6
      install:
        - pip install awscli coverage codecov
      script: bin/combine-coverage.sh
      after_success: codecov
    - stage: deploy
      python: 3.6
      install: true
      script: true
      after_success: true
      deploy:
        distributions: sdist bdist_wheel
        provider: pypi
        user: crad
        on:
          tags: true
        password:
          secure: "HW5Ak3scfeQ1/qdXQYrmIVnpGex59qNSGN2WRoHSFMXLfsjzdBQccy2nxWAo7p6P1wgoZ/51lTamJXGKgVqqQGC3gfBiD+AVMu3CROQht+Q4x5xKKLXQtTBoEOpurnx7q0oXRxhK7qmMOek9qqn/GGrK5PJV+pGoPwCvSTF6aic="
