language: python
dist: xenial
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - AWS_DEFAULT_REGION=us-east-1
    - secure: "HwRFY/PT2BkpcaxTpgvcZH7NVzFHB5bITEsdLNnAyyR1p6penesezg3VUnY5Bl91s4vP9sDFBZJC7AkAEOGTNAHJ0h1/2bEH3rQvi8WNnWFIjb5HbpZpfdHch+NO5kyEn7mUkcdyPpkI18JqlJLRcPKqNHpKqTuKt3FhrtfkfFs="
    - secure: "cE93hguZtiygLXcYAL/twX9zd9ELLmCepUUocYnV9JUxwZJ8s6jj4PXTXShXVl6KNY4pRViKNROfm+l0HzCrfi3C6BiRHBKP0zccGWSYRceEQFmK1irb+idsdz74J1DHA3KF+LNYaSBTSk5eU8o45WOx5p+bJ8P8QMRnIsybTgY="

stages:
  - test
  - name: upload coverage
    if: repo = gmr/pamqp
  - name: deploy
    if: tag IS present

install:
  - pip install -r requirements.txt
  - pip install awscli coverage
script: PYTHONWARNINGS=always nosetests
after_success: bin/upload-coverage.sh

jobs:
  include:
    - stage: upload coverage
      if: repo = gmr/pamqp
      python: 3.6
      install:
        - pip install awscli coverage codecov
      script: bin/combine-coverage.sh
      after_success: codecov
    - stage: deploy
      python: 3.6
      install: true
      script: true
      after_success: true
      deploy:
        distributions: sdist bdist_wheel
        provider: pypi
        user: crad
        on:
          tags: true
        password:
          secure: "HW5Ak3scfeQ1/qdXQYrmIVnpGex59qNSGN2WRoHSFMXLfsjzdBQccy2nxWAo7p6P1wgoZ/51lTamJXGKgVqqQGC3gfBiD+AVMu3CROQht+Q4x5xKKLXQtTBoEOpurnx7q0oXRxhK7qmMOek9qqn/GGrK5PJV+pGoPwCvSTF6aic="
